# Generated by Django 4.1.3 on 2022-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(max_length=150)),
                ('date', models.DateField(default=None)),
                ('high', models.FloatField(default=None)),
                ('low', models.FloatField(default=None)),
                ('open', models.FloatField(default=None)),
                ('close', models.FloatField(default=None)),
                ('volume', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
