# Generated by Django 4.1.3 on 2022-12-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.CharField(max_length=150),
        ),
    ]
